name: Build Android APK

on:
  push:
    branches: [ main, master, feat/PyQt6 ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      env:
        PIP_BREAK_SYSTEM_PACKAGES: 1
        APP_ANDROID_ACCEPT_SDK_LICENSE: 1
        USER: root
      with:
        command: buildozer android debug
        buildozer_version: stable
        workdir: .
    
    - name: Upload Android artifact
      uses: actions/upload-artifact@v4
      with:
        name: QR_Analyzer_Android
        path: ${{ steps.buildozer.outputs.filename }}
        retention-days: 7
        compression-level: 6
